<a href="https://www.kaggle.com/code/psuryateja/portfolio-project-1b-glassdoor-data-cleaning?scriptVersionId=136915761" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

file_path ="/kaggle/input/data-science-job-posting-on-glassdoor/Uncleaned_DS_jobs.csv"
print("Ready to Start")

Ready to Start

# Data Exploration
* Check the top Row
* Check the Number of columns & Row
* Find columns.Null-value,Datatypes (Useing info())
* Check Non-Null value,Duplicate values in Dataset (If dataset contain null-values or Duplicate values. Remove row Useing drop form Dataset)

In [2]:
uncleaned_data =pd.read_csv(file_path)

uncleaned_data.shape

(672, 15)

In [3]:
uncleaned_data.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [4]:
uncleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    object
 6   Location           672 non-null    object
 7   Headquarters       672 non-null    object
 8   Size               672 non-null    object
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    object
 11  Industry           672 non-null    object
 12  Sector             672 non-null    object
 13  Revenue            672 non-null    object
 14  Competitors        672 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 78.9+ KB

In [5]:
uncleaned_data.isnull().sum()

index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

No nulls , now lets try to find and remive the duplicate values , for this I need to delete the current index column cause when I delete the dublicates and by keeping the index column the values of index will also get deleted which makes the index column not continuous , we'll add a new index comlumn after deleting the duplicates

In [6]:
uncleaned_data.drop('index',axis=1,inplace=True)
uncleaned_data.shape

(672, 14)

In [7]:
print(uncleaned_data[uncleaned_data.duplicated()].shape)

uncleaned_data[uncleaned_data.duplicated()]

(13, 14)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
135,Machine Learning Engineer,$90K-$109K (Glassdoor est.),Role Description\nTriplebyte screens and evalu...,3.2,Triplebyte\n3.2,Remote,"San Francisco, CA",51 to 200 employees,2015,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
136,Senior Data Engineer,$90K-$109K (Glassdoor est.),Lendio is looking to fill a position for a Sen...,4.9,Lendio\n4.9,"Lehi, UT","Lehi, UT",201 to 500 employees,2011,Company - Private,Lending,Finance,$50 to $100 million (USD),-1
358,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
359,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
360,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
361,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
362,Data Scientist,$122K-$146K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
389,Data Scientist,$110K-$163K (Glassdoor est.),"Job Description\nAs a Data Scientist, you will...",-1.0,HireAi,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
496,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
497,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
498,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
499,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
500,Data Scientist,$95K-$119K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,-1.0,Hatch Data Inc,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1

* drop Duplicates values

In [8]:
uncleaned_data.drop_duplicates(inplace=True)

After Removeing Duplicate row remaining row

In [9]:
uncleaned_data.shape

(659, 14)

* After removeing Duplicate Reset_index

In [10]:
uncleaned_data.reset_index(inplace=True)
uncleaned_data.shape

(659, 15)

After Remove Null-values,Duplicate (DataSet)

In [11]:
uncleaned_data

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,667,Data Scientist,$105K-$167K (Glassdoor est.),Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT\n3.6,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
655,668,Data Scientist,$105K-$167K (Glassdoor est.),Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,-1,-1,-1,-1,-1
656,669,Data Scientist,$105K-$167K (Glassdoor est.),Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,-1,-1,-1,-1,-1
657,670,Data Scientist,$105K-$167K (Glassdoor est.),100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated\n5.0,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,Company - Private,Advertising & Marketing,Business Services,$1 to $5 million (USD),-1
658,671,Data Scientist,$105K-$167K (Glassdoor est.),Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers\n2.7,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,Company - Public,Wholesale,Business Services,$1 to $2 billion (USD),-1

# Removing Number in Company Name columns

In [12]:
uncleaned_data['Company Name']=uncleaned_data['Company Name'].apply(lambda x:x.split("\n")[0])

# Salary Estimate Column

* Check Values in ('Salary Estimate').column
* Create New columns (min salary,max salary,avg salary)
* Remove Extra symbols And character in Values

In [13]:
uncleaned_data['Salary Estimate'].value_counts()

$75K-$131K (Glassdoor est.)     32
$79K-$131K (Glassdoor est.)     32
$99K-$132K (Glassdoor est.)     32
$137K-$171K (Glassdoor est.)    30
$90K-$109K (Glassdoor est.)     28
$56K-$97K (Glassdoor est.)      22
$79K-$106K (Glassdoor est.)     22
$90K-$124K (Glassdoor est.)     22
$92K-$155K (Glassdoor est.)     21
$138K-$158K (Glassdoor est.)    21
$128K-$201K (Glassdoor est.)    21
$212K-$331K (Glassdoor est.)    21
$69K-$116K (Glassdoor est.)     21
$124K-$198K (Glassdoor est.)    21
$112K-$116K (Glassdoor est.)    21
$91K-$150K (Glassdoor est.)     21
$101K-$165K (Glassdoor est.)    21
$110K-$163K (Glassdoor est.)    20
$79K-$147K (Glassdoor est.)     20
$145K-$225K(Employer est.)      20
$31K-$56K (Glassdoor est.)      20
$141K-$225K (Glassdoor est.)    20
$66K-$112K (Glassdoor est.)     20
$80K-$132K (Glassdoor est.)     20
$87K-$141K (Glassdoor est.)     20
$105K-$167K (Glassdoor est.)    20
$79K-$133K (Glassdoor est.)     19
$71K-$123K (Glassdoor est.)     19
$122K-$146K (Glassdoor est.)    16
$95K-$119K (Glassdoor est.)     16
Name: Salary Estimate, dtype: int64

In [14]:
uncleaned_data['min_salary']=0
uncleaned_data['max_salary']=0
uncleaned_data['avg_salary']=0
for i in range(len(uncleaned_data)):
    try:
        uncleaned_data.loc[i,"min_salary"]=int(uncleaned_data['Salary Estimate'][i].split(" ")[0].split("-")[0].replace("$","").replace("K",""))
        uncleaned_data.loc[i,"max_salary"]=int(uncleaned_data['Salary Estimate'][i].split(" ")[0].split("-")[1].replace("$","").replace("K",""))
    except:
        uncleaned_data.loc[i,"min_salary"]=int(uncleaned_data['Salary Estimate'][i].split("(E")[0].split("-")[0].replace("$","").replace("K",""))
        uncleaned_data.loc[i,"max_salary"]=int(uncleaned_data['Salary Estimate'][i].split("(E")[0].split("-")[1].replace("$","").replace("K",""))
    finally:
        uncleaned_data.loc[i,"Salary Estimate"]=str(uncleaned_data.loc[i,"min_salary"])+"-"+str(uncleaned_data.loc[i,"max_salary"])
        uncleaned_data.loc[i,"avg_salary"]=np.mean([uncleaned_data.loc[i,"min_salary"],uncleaned_data.loc[i,"max_salary"]])

In [15]:
uncleaned_data.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0
1,1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0
2,2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0
3,3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0
4,4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0

# Exctract Data Job Description
* Create New Columns Based on Skill required for Job (Python,Excel,Sql,Tableau,Sparx,mechine learing,Aws) If Job description Contain Those skill in column print '1' otherwise '0' will print

In [16]:
uncleaned_data['Job Description'][0].split("\n\n")

['Description',
 'The Senior Data Scientist is responsible for defining, building, and improving statistical models to improve business processes and outcomes in one or more healthcare domains such as Clinical, Enrollment, Claims, and Finance. As part of the broader analytics team, Data Scientist will gather and analyze data to solve and address complex business problems and evaluate scenarios to make predictions on future outcomes and work with the business to communicate and support decision-making. This position requires strong analytical skills and experience in analytic methods including multivariate regressions, hierarchical linear models, regression trees, clustering methods and other complex statistical techniques.',
 'Duties & Responsibilities:',
 '• Develops advanced statistical models to predict, quantify or forecast various operational and performance metrics in multiple healthcare domains\n• Investigates, recommends, and initiates acquisition of new data resources from internal and external sources\n• Works with multiple teams to support data collection, integration, and retention requirements based on business needs\n• Identifies critical and emerging technologies that will support and extend quantitative analytic capabilities\n• Collaborates with business subject matter experts to select relevant sources of information\n• Develops expertise with multiple machine learning algorithms and data science techniques, such as exploratory data analysis and predictive modeling, graph theory, recommender systems, text analytics and validation\n• Develops expertise with Healthfirst datasets, data repositories, and data movement processes\n• Assists on projects/requests and may lead specific tasks within the project scope\n• Prepares and manipulates data for use in development of statistical models\n• Other duties as assigned',
 'Minimum Qualifications:',
 "-Bachelor's Degree",
 'Preferred Qualifications:',
 '- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience',
 'Minimum Qualifications:',
 "-Bachelor's Degree",
 'Preferred Qualifications:',
 '- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience',
 'WE ARE AN EQUAL OPPORTUNITY EMPLOYER. Applicants and employees are considered for positions and are evaluated without regard to mental or physical disability, race, color, religion, gender, national origin, age, genetic information, military or veteran status, sexual orientation, marital status or any other protected Federal, State/Province or Local status unrelated to the performance of the work involved.',
 'If you have a disability under the Americans with Disability Act or a similar law, and want a reasonable accommodation to assist with your job search or application for employment, please contact us by sending an email to careers@Healthfirst.org or calling 212-519-1798 . In your email please include a description of the accommodation you are requesting and a description of the position for which you are applying. Only reasonable accommodation requests related to applying for a position within Healthfirst Management Services will be reviewed at the e-mail address and phone number supplied. Thank you for considering a career with Healthfirst Management Services.\nEEO Law Poster and Supplement',
 ']]>']

In [17]:
uncleaned_data['python']=uncleaned_data['Job Description'].apply(lambda x: 1 if "python" in x.lower() else 0)
uncleaned_data['excel']=uncleaned_data['Job Description'].apply(lambda x: 1 if "excel" in x.lower() else 0)
uncleaned_data['Sql']=uncleaned_data['Job Description'].apply(lambda x: 1 if "sql" in x.lower() else 0)
uncleaned_data['tableau']=uncleaned_data['Job Description'].apply(lambda x: 1 if "tableau" in x.lower() else 0)
uncleaned_data['Sparx']=uncleaned_data['Job Description'].apply(lambda x: 1 if "Sparx" in x.lower() else 0)
uncleaned_data['machine learing']=uncleaned_data['Job Description'].apply(lambda x: 1 if "mechine learing" in x.lower() else 0)
uncleaned_data['aws']=uncleaned_data['Job Description'].apply(lambda x: 1 if "aws" in x.lower() else 0)

In [18]:
uncleaned_data

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,min_salary,max_salary,avg_salary,python,excel,Sql,tableau,Sparx,machine learing,aws
0,0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,...,137,171,154.0,0,0,0,0,0,0,1
1,1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,...,137,171,154.0,0,0,1,0,0,0,0
2,2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,...,137,171,154.0,1,1,0,0,0,0,1
3,3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,...,137,171,154.0,1,1,1,0,0,0,1
4,4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,...,137,171,154.0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,667,Data Scientist,105-167,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,1989,...,105,167,136.0,1,1,1,1,0,0,0
655,668,Data Scientist,105-167,Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,-1,...,105,167,136.0,0,0,0,0,0,0,0
656,669,Data Scientist,105-167,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,-1,...,105,167,136.0,1,1,1,1,0,0,0
657,670,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,-1,...,105,167,136.0,1,0,1,0,0,0,0
658,671,Data Scientist,105-167,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,1976,...,105,167,136.0,1,1,1,1,0,0,0

# Create New Column State Useing ['Location'] column

In [19]:
uncleaned_data['Location'].apply(lambda x:x.split(",")[-1]).value_counts()

 CA              154
 VA               89
 MA               62
 NY               52
 MD               40
 IL               30
 DC               26
 TX               17
 WA               16
 OH               14
 PA               12
 MO               12
United States     11
 NJ               10
 CO               10
 NC                9
 GA                9
 TN                8
 FL                8
 OK                6
 WI                6
Remote             5
 IN                5
 MI                5
 CT                4
 AL                4
 MN                4
 AZ                4
 NE                3
 IA                3
 RI                2
New Jersey         2
 SC                2
 OR                2
 UT                2
Utah               2
 NH                2
 MS                1
 LA                1
 KS                1
Texas              1
 DE                1
California         1
 WV                1
Name: Location, dtype: int64

In [20]:
uncleaned_data['State']= uncleaned_data['Location'].apply(lambda x:x.split(",")[-1].strip())
uncleaned_data['State'].replace(['United States','New Jersey','California','Texas ','Remote','Utah'],["US","NJ","CA","Tx",np.nan,np.nan],inplace=True)
uncleaned_data.dropna(axis=0,inplace= True)
uncleaned_data.reset_index(inplace= True)

# Create New Colum Employeetype Based on ['Job Titile']
* Based on the job title tag like sr, senior,lead,vp...etc find the employee is Senior or junior

In [21]:
uncleaned_data['Job Title'].value_counts()

Data Scientist                                            326
Data Engineer                                              26
Senior Data Scientist                                      19
Machine Learning Engineer                                  14
Data Analyst                                               12
                                                         ...
Business Data Analyst                                       1
Purification Scientist                                      1
Data Science Instructor                                     1
Data Engineer, Enterprise Analytics                         1
AI/ML - Machine Learning Scientist, Siri Understanding      1
Name: Job Title, Length: 168, dtype: int64

In [22]:
def employeetype(job_title):
    job_title=job_title.lower()
    emp=['sr','senior','lead','principal','vp','vice president','director']
    for i in emp:
        if i in job_title:
            return "Senior_emp"
        else:
            return "junior_emp"
    return NaN

In [23]:
uncleaned_data['Employee expriece ']= uncleaned_data['Job Title'].apply(employeetype)
uncleaned_data

,level_0,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,...,avg_salary,python,excel,Sql,tableau,Sparx,machine learing,aws,State,Employee expriece
0,0,0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,...,154.0,0,0,0,0,0,0,1,NY,Senior_emp
1,1,1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,...,154.0,0,0,1,0,0,0,0,VA,junior_emp
2,2,2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,...,154.0,1,1,0,0,0,0,1,MA,junior_emp
3,3,3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,...,154.0,1,1,1,0,0,0,1,MA,junior_emp
4,4,4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,...,154.0,1,1,1,0,0,0,0,NY,junior_emp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,654,667,Data Scientist,105-167,Summary\n\nWe’re looking for a data scientist ...,3.6,TRANZACT,"Fort Lee, NJ","Fort Lee, NJ",1001 to 5000 employees,...,136.0,1,1,1,1,0,0,0,NJ,junior_emp
648,655,668,Data Scientist,105-167,Job Description\nBecome a thought leader withi...,-1.0,JKGT,"San Francisco, CA",-1,-1,...,136.0,0,0,0,0,0,0,0,CA,junior_emp
649,656,669,Data Scientist,105-167,Join a thriving company that is changing the w...,-1.0,AccessHope,"Irwindale, CA",-1,-1,...,136.0,1,1,1,1,0,0,0,CA,junior_emp
650,657,670,Data Scientist,105-167,100 Remote Opportunity As an AINLP Data Scient...,5.0,ChaTeck Incorporated,"San Francisco, CA","Santa Clara, CA",1 to 50 employees,...,136.0,1,0,1,0,0,0,0,CA,junior_emp
651,658,671,Data Scientist,105-167,Description\n\nThe Data Scientist will be part...,2.7,1-800-Flowers,"New York, NY","Carle Place, NY",1001 to 5000 employees,...,136.0,1,1,1,1,0,0,0,NY,junior_emp

# Conclusion
Export File into PC In CSV format

In [24]:
uncleaned_data.to_csv('Data_science Job',index=False)